### PR TITLE
Fix UnionPath

### PR DESCRIPTION
**Pull request by noeppi-noeppi**
Currently `UnionPath#relativize` gives wrong results for absolute paths as a simple test program shows:

```java
Path regularBase = Paths.get("/example/path");
Path regularPath = Paths.get("/example/path/with/a/few/elements");
System.out.println(regularBase.relativize(regularPath));

FileSystem fs = new UnionFileSystemProvider().newFileSystem(URI.create("union:file:/"), Map.of("filter", (BiPredicate<String, String>) (p, b) -> true));
Path unionBase = fs.getPath("/example/path");
Path unionPath = fs.getPath("/example/path/with/a/few/elements");
System.out.println(unionBase.relativize(unionPath));
```

which gives

```
with/a/few/elements
path/with/a/few/elements
```

where you see the intended behavior in the top line and the behavior with union path in the second line.

This is because when creating a subpath in `relativize`, `poff` is not added to the start index, so the resulting path will always have one element more than it should because of the empty root component.

Another thing I saw is that it is valid to relativize a non-absolute path with an absolute path which should not be allowed. This is not addressed by the pull request for now because I'm not certain whether It can safely be merged or might break existing code somewhere else.

### CODE REVIEW

**Comment by noeppi-noeppi** [comment]
Noticed that other methods (like `getNameCount` and `subPath` also don't work as expected on absolute paths. I'll make this a draft until they are fixed as well

**Comment by LexManos** [comment]
I've been meaning to get around to reviewing this. But haven't had the time to sit down and read the NIO specs on what these functions should actually return.
Sorry.
I'm sure there are several small cases where things could be fixed up.

**Comment by noeppi-noeppi** [comment]
Should be done now, however it breaks stuff when actually using it together with modlauncher. By that I also noticed that `ServiceLoaderUtils#fileNameFor` seems to not have worked correctly until now either. So I'll open a pull request on modlauncher (and maybe forge, depending on whether it breaks with these changes) as well.
When it is working, I'll mark this as ready for review.

**Comment by noeppi-noeppi** [comment]
I made it work without changes in modlauncher or forge. Should be ready for review now.

**Comment by cpw** [comment]
Does this interact with #18 at all?

**Comment by amadornes** [comment]
I've been looking through the code and they shouldn't clash.

Just in case, I just tried merging both PRs locally and all tests pass.

**Pull request merged**
